-- AlterEnum
ALTER TYPE "WicketType" ADD VALUE 'RETIRED_OUT';
ALTER TYPE "WicketType" ADD VALUE 'HIT_BALL_TWICE';
ALTER TYPE "WicketType" ADD VALUE 'OBSTRUCTING_FIELD';

-- AlterTable
ALTER TABLE "BallEvent" ADD COLUMN     "byeRuns" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "legByeRuns" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Innings" ADD COLUMN     "isAllOut" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "maxWickets" INTEGER;
